-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.add_ons
(
    addon_id integer NOT NULL DEFAULT nextval('add_ons_id_seq'::regclass),
    client_id integer,
    amount double precision,
    date date,
    invoice_number character varying COLLATE pg_catalog."default",
    created_at date,
    group_id character varying COLLATE pg_catalog."default",
    items jsonb,
    vat_applied boolean DEFAULT true,
    booking_ref character varying(50) COLLATE pg_catalog."default",
    client_ref character varying(50) COLLATE pg_catalog."default",
    paid_amount numeric(12, 2) DEFAULT 0,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'unpaid'::character varying,
    vessel_number character varying COLLATE pg_catalog."default",
    CONSTRAINT add_ons_pkey PRIMARY KEY (addon_id)
);

CREATE TABLE IF NOT EXISTS public.aging_analysis
(
    aging_key serial NOT NULL,
    clientid integer NOT NULL,
    current numeric,
    "30days" numeric,
    "60days" numeric,
    "90days" numeric,
    CONSTRAINT aging_analysis_pkey PRIMARY KEY (aging_key)
);

CREATE TABLE IF NOT EXISTS public.audit_log
(
    id serial NOT NULL,
    action_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    admin_id integer,
    target_employee_id integer,
    target_employee_name character varying(255) COLLATE pg_catalog."default",
    "timestamp" timestamp with time zone DEFAULT now(),
    details text COLLATE pg_catalog."default",
    ip_address inet,
    user_agent text COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT audit_log_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE public.audit_log
    IS 'Audit trail for tracking administrative actions on employee records';

COMMENT ON COLUMN public.audit_log.action_type
    IS 'Type of action performed (e.g., PASSWORD_CHANGE, EMPLOYEE_CREATION)';

COMMENT ON COLUMN public.audit_log.admin_id
    IS 'ID of the administrator who performed the action';

COMMENT ON COLUMN public.audit_log.target_employee_id
    IS 'ID of the employee the action was performed on';

COMMENT ON COLUMN public.audit_log.target_employee_name
    IS 'Name of the employee for easy identification';

COMMENT ON COLUMN public.audit_log."timestamp"
    IS 'When the action occurred';

COMMENT ON COLUMN public.audit_log.details
    IS 'Additional details about the action in human-readable format';

COMMENT ON COLUMN public.audit_log.ip_address
    IS 'IP address of the administrator for enhanced security tracking';

COMMENT ON COLUMN public.audit_log.user_agent
    IS 'Browser/client information for enhanced security tracking';

CREATE TABLE IF NOT EXISTS public.base_salary_history
(
    id serial NOT NULL,
    userid integer,
    base double precision,
    date date,
    CONSTRAINT base_salary_history_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.container
(
    containerkey serial NOT NULL,
    containernum character varying(20) COLLATE pg_catalog."default",
    weight double precision,
    m1key integer,
    container_type text COLLATE pg_catalog."default",
    cargo_description text COLLATE pg_catalog."default",
    "Add Surcharges" boolean,
    "Hazardous" boolean,
    "Surcharge Amount" double precision,
    "Hazardous Amount" double precision,
    file_ref character varying COLLATE pg_catalog."default",
    "vgm amount" double precision,
    vgm boolean,
    is_12m_surcharge boolean NOT NULL DEFAULT false,
    surcharge_12m_amount numeric(12, 2) NOT NULL DEFAULT 0,
    CONSTRAINT container_pkey PRIMARY KEY (containerkey)
);

CREATE TABLE IF NOT EXISTS public.credit_notes
(
    creditnote_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    client_id integer NOT NULL,
    creditnote_date date NOT NULL DEFAULT CURRENT_DATE,
    amount double precision[] NOT NULL,
    containerids integer[] NOT NULL,
    doc_no character varying(50) COLLATE pg_catalog."default",
    m1key integer,
    description text COLLATE pg_catalog."default",
    account_no character varying(50) COLLATE pg_catalog."default",
    vat double precision,
    CONSTRAINT credit_notes_pkey PRIMARY KEY (creditnote_id)
);

CREATE TABLE IF NOT EXISTS public.documents
(
    document_id serial NOT NULL,
    name text COLLATE pg_catalog."default",
    type text COLLATE pg_catalog."default",
    leg_number integer,
    s3key text COLLATE pg_catalog."default",
    upload_date date,
    m1key integer,
    client integer,
    url text COLLATE pg_catalog."default",
    CONSTRAINT documents_pkey PRIMARY KEY (document_id)
);

CREATE TABLE IF NOT EXISTS public.employee_deduction_history
(
    history_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    employeeid integer NOT NULL,
    effective_date date NOT NULL,
    income_tax_rate double precision,
    deduction_income_tax double precision,
    deduction_other_deductions double precision,
    deduction_uif double precision,
    deduction_bonus double precision,
    deduction_savings double precision,
    deduction_loan double precision,
    deduction_damage double precision,
    CONSTRAINT employee_deduction_history_pkey PRIMARY KEY (history_id)
);

CREATE TABLE IF NOT EXISTS public.expense_types
(
    id serial NOT NULL,
    expense text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT expense_types_pkey PRIMARY KEY (id),
    CONSTRAINT expense_types_name_key UNIQUE (expense)
);

CREATE TABLE IF NOT EXISTS public.expenses_m2
(
    ekey serial NOT NULL,
    type text COLLATE pg_catalog."default",
    documentfrom text COLLATE pg_catalog."default",
    expensecost double precision,
    description text COLLATE pg_catalog."default",
    slipname text COLLATE pg_catalog."default",
    slipuploaddate date,
    truckid integer,
    driverid integer,
    slipurl text COLLATE pg_catalog."default",
    s3key text COLLATE pg_catalog."default",
    orderno character varying COLLATE pg_catalog."default",
    CONSTRAINT expenses_m2_pkey PRIMARY KEY (ekey),
    CONSTRAINT expenses_m2_orderno_unique UNIQUE (orderno)
);

CREATE TABLE IF NOT EXISTS public.invoice
(
    ikey serial NOT NULL,
    clientid integer,
    m1key integer,
    invoice_num text COLLATE pg_catalog."default",
    doc_num text COLLATE pg_catalog."default",
    groupid character varying(20) COLLATE pg_catalog."default",
    date date,
    additional_destination_info character varying COLLATE pg_catalog."default",
    CONSTRAINT invoice_pkey PRIMARY KEY (ikey)
);

CREATE TABLE IF NOT EXISTS public.legs_m2
(
    legkey serial NOT NULL,
    legnumber integer,
    driverid integer,
    truckregnumber character varying(20) COLLATE pg_catalog."default",
    containernumber character varying(20) COLLATE pg_catalog."default",
    date date,
    startingpoint text COLLATE pg_catalog."default",
    destination text COLLATE pg_catalog."default",
    driverrate double precision,
    vgm double precision,
    legstatus text COLLATE pg_catalog."default",
    documentname text COLLATE pg_catalog."default",
    documenttype text COLLATE pg_catalog."default",
    documentuploaddate date,
    m1key integer,
    m5ratekey integer,
    CONSTRAINT legs_m2_pkey PRIMARY KEY (legkey),
    CONSTRAINT legs_m2_unique_assignment UNIQUE (m1key, legnumber, driverid, truckregnumber, containernumber, vgm, date)
);

CREATE TABLE IF NOT EXISTS public.m1_controller
(
    m1key serial NOT NULL,
    client integer,
    "ksmFileRef" text COLLATE pg_catalog."default",
    shipment_type integer,
    pickup text COLLATE pg_catalog."default",
    dropoff text COLLATE pg_catalog."default",
    stackdate date,
    "lastFreeDate" date,
    "clientFileRef" text COLLATE pg_catalog."default",
    rateweight text COLLATE pg_catalog."default",
    description character varying(225) COLLATE pg_catalog."default",
    status text COLLATE pg_catalog."default",
    vat integer,
    num_six_meters integer,
    num_twelve_meters integer,
    num_abnormal integer,
    total_cost double precision,
    weight double precision,
    booking_ref text COLLATE pg_catalog."default",
    vessel_name text COLLATE pg_catalog."default",
    rateper_6 double precision,
    rateper_12 double precision,
    rateper_abnormal double precision,
    surcharge double precision,
    unitrate double precision,
    num_breakbulk integer,
    rateper_breakbulk double precision,
    created_at date,
    paid_amount numeric(12, 2) DEFAULT 0,
    payment_status character varying(20) COLLATE pg_catalog."default" DEFAULT 'unpaid'::character varying,
    is_set_rate boolean NOT NULL DEFAULT false,
    historical_set_rate numeric(10, 2),
    CONSTRAINT m1_controller_pkey PRIMARY KEY (m1key)
);

CREATE TABLE IF NOT EXISTS public.m1_controller_weight
(
    weight_pk integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    m1_key integer,
    ksm_dm_no character varying COLLATE pg_catalog."default",
    ticket_no character varying COLLATE pg_catalog."default",
    receipt_book_no character varying COLLATE pg_catalog."default",
    weight double precision,
    CONSTRAINT m1_controller_weight_pkey PRIMARY KEY (weight_pk)
);

CREATE TABLE IF NOT EXISTS public.m5_client
(
    m5clientkey serial NOT NULL,
    client text COLLATE pg_catalog."default",
    representative text COLLATE pg_catalog."default",
    companyaddress text COLLATE pg_catalog."default",
    suburb text COLLATE pg_catalog."default",
    postalcode text COLLATE pg_catalog."default",
    email text COLLATE pg_catalog."default",
    client_reg_num character varying(100) COLLATE pg_catalog."default",
    cellnum character varying(10) COLLATE pg_catalog."default",
    vatregno character varying(20) COLLATE pg_catalog."default",
    city text COLLATE pg_catalog."default",
    streetaddress text COLLATE pg_catalog."default",
    payment_type text COLLATE pg_catalog."default",
    status boolean NOT NULL DEFAULT true,
    starting_point character varying(250) COLLATE pg_catalog."default",
    destination character varying(250) COLLATE pg_catalog."default",
    driver_six_meter_rate double precision,
    driver_twelve_meter_rate double precision,
    insurance numeric(12, 2),
    CONSTRAINT m5_client_pkey PRIMARY KEY (m5clientkey)
);

CREATE TABLE IF NOT EXISTS public.m5_client_rate
(
    client_rate_id serial NOT NULL,
    starting_point character varying COLLATE pg_catalog."default",
    destination character varying COLLATE pg_catalog."default",
    "6m_rate" double precision,
    "12m_rate" double precision,
    surcharges double precision,
    clientid integer,
    hazardous double precision,
    vgm double precision,
    set_rate double precision,
    surcharge12m double precision,
    CONSTRAINT m5_client_rate_pkey PRIMARY KEY (client_rate_id)
);

CREATE TABLE IF NOT EXISTS public.m5_driver_rate
(
    m5ratekey serial NOT NULL,
    startingpoint text COLLATE pg_catalog."default",
    destination text COLLATE pg_catalog."default",
    driverid integer,
    subie_rate double precision,
    driver_six_meter_rate double precision,
    driver_twelve_meter_rate double precision,
    subie_six_meter_rate double precision,
    subie_twelve_meter_rate double precision,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    effective_from date NOT NULL DEFAULT '2020-01-01'::date,
    effective_to date,
    CONSTRAINT m5_driver_rate_pkey PRIMARY KEY (m5ratekey)
);

CREATE TABLE IF NOT EXISTS public.m5_employee
(
    userid integer NOT NULL DEFAULT nextval('m5_merged_userid_seq'::regclass),
    name text COLLATE pg_catalog."default",
    surname text COLLATE pg_catalog."default",
    telephonenum character varying(10) COLLATE pg_catalog."default",
    cellnum character varying(10) COLLATE pg_catalog."default",
    employeenum character varying(20) COLLATE pg_catalog."default",
    roleid integer,
    email text COLLATE pg_catalog."default",
    password text COLLATE pg_catalog."default",
    base_salary double precision,
    companyname text COLLATE pg_catalog."default",
    location text COLLATE pg_catalog."default",
    truckregnum text COLLATE pg_catalog."default",
    contact_person character varying(25) COLLATE pg_catalog."default",
    subei_reg_num character varying(20) COLLATE pg_catalog."default",
    no_of_trucks integer,
    status boolean,
    company_reg_num character varying(20) COLLATE pg_catalog."default",
    subdrivername text[] COLLATE pg_catalog."default",
    income_tax_rate double precision,
    deduction_income_tax double precision,
    deduction_other_deductions double precision,
    deduction_uif double precision,
    deduction_bonus double precision,
    deduction_savings double precision,
    deduction_loan double precision,
    deduction_damage double precision,
    loan_amount double precision,
    deduction_date date,
    document_url1 character varying COLLATE pg_catalog."default",
    document_url2 character varying COLLATE pg_catalog."default",
    document_url3 character varying COLLATE pg_catalog."default",
    driverstatus boolean DEFAULT false,
    CONSTRAINT m5_merged_pkey PRIMARY KEY (userid)
);

CREATE TABLE IF NOT EXISTS public.m5_trailers
(
    m5trailerskey serial NOT NULL,
    trailerregnum character varying(20) COLLATE pg_catalog."default",
    trailersize character varying(20) COLLATE pg_catalog."default",
    trailerpurchasedate date,
    year integer,
    model character varying(50) COLLATE pg_catalog."default",
    purchase_price double precision,
    current_evaluation character varying(20) COLLATE pg_catalog."default",
    vin_num character varying(255) COLLATE pg_catalog."default",
    document_url1 character varying COLLATE pg_catalog."default",
    document_url2 character varying COLLATE pg_catalog."default",
    document_url3 character varying COLLATE pg_catalog."default",
    trailer_license_expiry date,
    status boolean DEFAULT true,
    CONSTRAINT m5_trailers_pkey PRIMARY KEY (m5trailerskey)
);

COMMENT ON COLUMN public.m5_trailers.trailer_license_expiry
    IS 'Date when the trailer license expires - used for 30-day expiry notifications';

COMMENT ON COLUMN public.m5_trailers.status
    IS 'Trailer status: true = enabled, false = disabled';

CREATE TABLE IF NOT EXISTS public.m5_trucks
(
    m5truckskey serial NOT NULL,
    truckregnum character varying(20) COLLATE pg_catalog."default",
    trailersize character varying(20) COLLATE pg_catalog."default",
    truckpurchasedate date,
    year integer,
    model character varying(50) COLLATE pg_catalog."default",
    purchase_price double precision,
    current_evaluation character varying(20) COLLATE pg_catalog."default",
    vin_num character varying(20) COLLATE pg_catalog."default",
    is_subcontractor boolean,
    document_url1 character varying COLLATE pg_catalog."default",
    document_url2 character varying COLLATE pg_catalog."default",
    document_url3 character varying COLLATE pg_catalog."default",
    truck_license_expiry date,
    subei_reg_num character varying(250) COLLATE pg_catalog."default",
    git character varying(255) COLLATE pg_catalog."default",
    status boolean DEFAULT true,
    CONSTRAINT m5_trucks_pkey PRIMARY KEY (m5truckskey)
);

COMMENT ON COLUMN public.m5_trucks.truck_license_expiry
    IS 'Date when the truck license expires - used for 30-day expiry notifications';

COMMENT ON COLUMN public.m5_trucks.subei_reg_num
    IS 'Reference to subcontractor registration number when is_subcontractor is true';

COMMENT ON COLUMN public.m5_trucks.status
    IS 'Truck status: true = active, false = disabled';

CREATE TABLE IF NOT EXISTS public.payment_m3
(
    paykey serial NOT NULL,
    amount double precision,
    filename text COLLATE pg_catalog."default",
    fileupload date,
    clientid integer,
    invoiceid integer,
    reference character varying COLLATE pg_catalog."default",
    addon_id integer,
    line_items jsonb,
    CONSTRAINT payment_m3_pkey PRIMARY KEY (paykey)
);

CREATE TABLE IF NOT EXISTS public.purchase_orders
(
    po_id serial NOT NULL,
    supplier_id integer NOT NULL,
    reg_no text COLLATE pg_catalog."default",
    attention_to text COLLATE pg_catalog."default",
    received_by text COLLATE pg_catalog."default",
    quantity integer NOT NULL,
    unit_price double precision NOT NULL,
    description text COLLATE pg_catalog."default",
    subbie text COLLATE pg_catalog."default",
    date date,
    ponum text COLLATE pg_catalog."default",
    total double precision,
    expense_type_id integer,
    orderno character varying COLLATE pg_catalog."default",
    slip_s3key text COLLATE pg_catalog."default",
    invoice_number character varying COLLATE pg_catalog."default",
    truckid integer,
    vat double precision,
    CONSTRAINT purchase_orders_pkey PRIMARY KEY (po_id)
);

CREATE TABLE IF NOT EXISTS public.roles
(
    roleid serial NOT NULL,
    rolename text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT roles_pkey PRIMARY KEY (roleid),
    CONSTRAINT roles_rolename_key UNIQUE (rolename)
);

CREATE TABLE IF NOT EXISTS public.shipment
(
    shipkey serial NOT NULL,
    shipmenttype text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT shipment_pkey PRIMARY KEY (shipkey),
    CONSTRAINT shipment_shipmenttype_key UNIQUE (shipmenttype)
);

CREATE TABLE IF NOT EXISTS public.statements
(
    statement_key serial NOT NULL,
    groupid character varying(20) COLLATE pg_catalog."default",
    generation_date date DEFAULT CURRENT_DATE,
    clientid integer,
    agingid integer,
    opening_balance numeric,
    insurance_amount numeric(12, 2) DEFAULT 0,
    CONSTRAINT statements_pkey PRIMARY KEY (statement_key)
);

CREATE TABLE IF NOT EXISTS public.subcontractor_statements
(
    sub_state_id serial NOT NULL,
    subbie_reg_num character varying COLLATE pg_catalog."default",
    date date,
    amount numeric,
    legids json,
    vat_status character varying COLLATE pg_catalog."default" DEFAULT 'VAT'::character varying,
    CONSTRAINT subcontractor_statements_pkey PRIMARY KEY (sub_state_id)
);

CREATE TABLE IF NOT EXISTS public.supplier_expense_types
(
    se_id integer NOT NULL,
    expense_type_id integer NOT NULL,
    CONSTRAINT supplier_expense_types_pkey PRIMARY KEY (se_id, expense_type_id)
);

CREATE TABLE IF NOT EXISTS public.suppliers
(
    supplier_id serial NOT NULL,
    supplier text COLLATE pg_catalog."default" NOT NULL,
    representative text COLLATE pg_catalog."default" NOT NULL,
    address text COLLATE pg_catalog."default",
    suburb text COLLATE pg_catalog."default",
    postalcode text COLLATE pg_catalog."default",
    email text COLLATE pg_catalog."default",
    cellnum character varying(20) COLLATE pg_catalog."default",
    vatregno character varying(20) COLLATE pg_catalog."default",
    city text COLLATE pg_catalog."default",
    streetaddress text COLLATE pg_catalog."default",
    payment_type text COLLATE pg_catalog."default",
    status boolean NOT NULL DEFAULT true,
    CONSTRAINT suppliers_pkey PRIMARY KEY (supplier_id)
);

CREATE TABLE IF NOT EXISTS public.tax_deductions
(
    id serial NOT NULL,
    remuneration_lower double precision NOT NULL,
    remuneration_upper double precision NOT NULL,
    tax double precision NOT NULL,
    effective_date date,
    CONSTRAINT tax_deductions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.usertable
(
    userid serial NOT NULL,
    name text COLLATE pg_catalog."default",
    surname text COLLATE pg_catalog."default",
    email text COLLATE pg_catalog."default",
    password text COLLATE pg_catalog."default",
    companyname text COLLATE pg_catalog."default",
    dateofreg date,
    status text COLLATE pg_catalog."default",
    roleid integer,
    company_reg_num character varying(20) COLLATE pg_catalog."default",
    cluster_box text COLLATE pg_catalog."default",
    cell_num character varying(10) COLLATE pg_catalog."default",
    cell_num2 character varying(10) COLLATE pg_catalog."default",
    vat_reg_num character varying(20) COLLATE pg_catalog."default",
    account_num text COLLATE pg_catalog."default",
    name_of_acc text COLLATE pg_catalog."default",
    bank text COLLATE pg_catalog."default",
    branch text COLLATE pg_catalog."default",
    branch_code text COLLATE pg_catalog."default",
    address text COLLATE pg_catalog."default",
    suburb text COLLATE pg_catalog."default",
    swift_code character varying(11) COLLATE pg_catalog."default",
    CONSTRAINT usertable_pkey PRIMARY KEY (userid),
    CONSTRAINT usertable_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.wages
(
    wageskey serial NOT NULL,
    salary_hours integer,
    salary_rate double precision,
    salary_total double precision,
    overtime_hours integer,
    overtime_rate double precision,
    overtime_total double precision,
    public_holidays_days integer,
    public_holidays_rate double precision,
    public_holidays_total double precision,
    allowance_rate double precision,
    allowance_total double precision,
    short_pay_rate double precision,
    short_pay_total double precision,
    total_earnings double precision,
    total_deductions double precision,
    net_pay double precision,
    employeeid integer,
    employee_date date,
    employerid integer,
    employer_date date,
    CONSTRAINT wages_pkey PRIMARY KEY (wageskey),
    CONSTRAINT unique_wage_per_employee_month_year UNIQUE (employeeid, employee_date)
);

ALTER TABLE IF EXISTS public.add_ons
    ADD CONSTRAINT fk_client FOREIGN KEY (client_id)
    REFERENCES public.m5_client (m5clientkey) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.aging_analysis
    ADD CONSTRAINT clientid FOREIGN KEY (clientid)
    REFERENCES public.m5_client (m5clientkey) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.base_salary_history
    ADD CONSTRAINT employeeid FOREIGN KEY (userid)
    REFERENCES public.m5_employee (userid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.container
    ADD CONSTRAINT container_m1key_fkey FOREIGN KEY (m1key)
    REFERENCES public.m1_controller (m1key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.credit_notes
    ADD CONSTRAINT fk_credit_notes_client_id FOREIGN KEY (client_id)
    REFERENCES public.m5_client (m5clientkey) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.credit_notes
    ADD CONSTRAINT fk_credit_notes_m1key FOREIGN KEY (m1key)
    REFERENCES public.m1_controller (m1key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.documents
    ADD CONSTRAINT documents_client_fkey FOREIGN KEY (client)
    REFERENCES public.m5_client (m5clientkey) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.documents
    ADD CONSTRAINT documents_m1key_fkey FOREIGN KEY (m1key)
    REFERENCES public.m1_controller (m1key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.employee_deduction_history
    ADD CONSTRAINT fk_employee_history FOREIGN KEY (employeeid)
    REFERENCES public.m5_employee (userid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.expenses_m2
    ADD CONSTRAINT fk_expenses_driver FOREIGN KEY (driverid)
    REFERENCES public.m5_employee (userid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.expenses_m2
    ADD CONSTRAINT fk_expenses_truck FOREIGN KEY (truckid)
    REFERENCES public.m5_trucks (m5truckskey) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.invoice
    ADD CONSTRAINT invoice_clientid_fkey FOREIGN KEY (clientid)
    REFERENCES public.m5_client (m5clientkey) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.invoice
    ADD CONSTRAINT invoice_m1key_fkey FOREIGN KEY (m1key)
    REFERENCES public.m1_controller (m1key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.legs_m2
    ADD CONSTRAINT legs_m2_driverid_fkey FOREIGN KEY (driverid)
    REFERENCES public.m5_employee (userid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.legs_m2
    ADD CONSTRAINT legs_m2_m1key_fkey FOREIGN KEY (m1key)
    REFERENCES public.m1_controller (m1key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.legs_m2
    ADD CONSTRAINT legs_m2_m5ratekey_fkey FOREIGN KEY (m5ratekey)
    REFERENCES public.m5_driver_rate (m5ratekey) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.m1_controller
    ADD CONSTRAINT m1_controller_client_fkey FOREIGN KEY (client)
    REFERENCES public.m5_client (m5clientkey) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.m1_controller
    ADD CONSTRAINT m1_controller_shipment_type_fkey FOREIGN KEY (shipment_type)
    REFERENCES public.shipment (shipkey) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.m1_controller_weight
    ADD CONSTRAINT m1_controller_weight_m1_key_fkey FOREIGN KEY (m1_key)
    REFERENCES public.m1_controller (m1key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.m5_client_rate
    ADD CONSTRAINT clientid FOREIGN KEY (clientid)
    REFERENCES public.m5_client (m5clientkey) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.m5_driver_rate
    ADD CONSTRAINT m5_driver_rate_driverid_fkey FOREIGN KEY (driverid)
    REFERENCES public.m5_employee (userid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.m5_employee
    ADD CONSTRAINT fk_employee_role FOREIGN KEY (roleid)
    REFERENCES public.roles (roleid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.payment_m3
    ADD CONSTRAINT payment_m3_clientid_fkey FOREIGN KEY (clientid)
    REFERENCES public.m5_client (m5clientkey) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.payment_m3
    ADD CONSTRAINT payment_m3_invoiceid_fkey FOREIGN KEY (invoiceid)
    REFERENCES public.invoice (ikey) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.purchase_orders
    ADD CONSTRAINT purchase_orders_expense_type_id_fkey FOREIGN KEY (expense_type_id)
    REFERENCES public.expense_types (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.purchase_orders
    ADD CONSTRAINT purchase_orders_supplier_id_fkey FOREIGN KEY (supplier_id)
    REFERENCES public.suppliers (supplier_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.statements
    ADD CONSTRAINT agingid FOREIGN KEY (agingid)
    REFERENCES public.aging_analysis (aging_key) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.supplier_expense_types
    ADD CONSTRAINT supplier_expense_types_expense_type_id_fkey FOREIGN KEY (expense_type_id)
    REFERENCES public.expense_types (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.supplier_expense_types
    ADD CONSTRAINT supplier_expense_types_supplier_pk_fkey FOREIGN KEY (se_id)
    REFERENCES public.suppliers (supplier_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.usertable
    ADD CONSTRAINT usertable_roleid_fkey FOREIGN KEY (roleid)
    REFERENCES public.roles (roleid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.wages
    ADD CONSTRAINT wages_employeeid_fkey FOREIGN KEY (employeeid)
    REFERENCES public.m5_employee (userid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.wages
    ADD CONSTRAINT wages_employerid_fkey FOREIGN KEY (employerid)
    REFERENCES public.m5_employee (userid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;

END;