import express from "express";
import authroutes from "./auth/authRoutes.js";
import adminroutes from "./admin/adminRoutes.js";
import testroutes from "./test/testRoutes.js";
import manageEmployeeRoutes from "./manage/employeeRoutes.js";
import manageClientRoutes from "./manage/clientRoutes.js";
import manageTruckRoutes from "./manage/truckRoutes.js";
import manageDriverRatesRoutes from "./manage/driverRatesRoutes.js";
import manageSubbieRoutes from "./manage/subbieRoutes.js";
import manageTrailerRoutes from "./manage/trailerRoutes.js";
import supplierRoutes from "./manage/supplierRoutes.js";
import expenseTypeRoutes from "./manage/expenseTypeRoutes.js";
import manageClientRateRoutes from "./manage/clientRateRoutes.js";
import manageCompanyRoutes from "./manage/companyRoutes.js";
import paymentRoutes from "./payments/paymentRoutes.js";
import clientRoutes from "./clients/clientRoutes.js";
import invoiceRoutes from "./invoices/invoiceRoutes.js";
import statementRoutes from "./statements/statementRoutes.js";
import statementInvoiceRoutes from "./statement-invoice/clientInstructionRoutes.js";
import wagesRoutes from "./wages/wageRoutes.js";
import analyticsRoutes from "./analytics/analyticsRoutes.js";
import employeeRoutes from "./empoloyees/employeeRoutes.js";
import driverRoutes from "./drivers/driverRoutes.js";
import documentRoutes from "./assignments/documentRoutes.js";
import fuelSlipRoutes from "./fuel/expensesRoutes.js";
import fuelRoutes from "./fuel/fuelRoutes.js";
import purchaseOrderRoutes from "./purchaseOrder/purchaseOrderRoutes.js";
import instructionRoutes from "./instructions/instructionRoutes.js";
import assignmentRoutes from "./assignments/assignmentRoutes.js";
import subcontractorsRoutes from "./subcontractors/subContractorRoutes.js";
import addonRoutes from "./add-ons/addonRoutes.js";
import creditNoteRoutes from "./creditNote/creditNoteRoutes.js";

const router = express.Router();

router.use(creditNoteRoutes);
router.use(authroutes);
router.use(adminroutes);
router.use(testroutes);
router.use(manageEmployeeRoutes);
router.use(manageClientRoutes);
router.use(manageTruckRoutes);
router.use(manageDriverRatesRoutes);
router.use(manageSubbieRoutes);
router.use(manageTrailerRoutes);
router.use(manageClientRateRoutes);
router.use(manageCompanyRoutes);
router.use(supplierRoutes);
router.use(expenseTypeRoutes);
router.use(invoiceRoutes);
router.use(paymentRoutes);
router.use(clientRoutes);
router.use(statementRoutes);
router.use(statementInvoiceRoutes);
router.use(wagesRoutes);
router.use(analyticsRoutes);
router.use(employeeRoutes);
router.use(driverRoutes);
router.use("/documents", documentRoutes);
router.use("/expenses", fuelSlipRoutes);
router.use(fuelRoutes);
router.use(purchaseOrderRoutes);
router.use("/api/instructions", instructionRoutes);
router.use(assignmentRoutes);
router.use(subcontractorsRoutes);
router.use(addonRoutes);

export default router;
